#!/bin/bash
#rm -f 0-code/nu-tmp-*
#rm -f results/nu-batch.e*
#rm -f results/nu-batch.o*

PREFIX="results\/nu-batch"

# Find out which jobs are currently running
JOBS=$(qstat | grep jkopp | \
       sed -n -e "s/^.\{7\}\([0-9]\{6,7\}\).*$/$PREFIX.o\1\\n$PREFIX.e\1\\n/ p" -)
ALL_FILES=$(ls $PREFIX.*)

#NUTMP_LIST=""
for FILE in $ALL_FILES; do
  if [[ -z $(echo "$JOBS" | grep "$FILE") ]]; then
#    NUTMP_FILE=$(sed -n -e "s/Executable: *\(.*\)$/\1/ p" $FILE)
#    if [[ -n $NUTMP_FILE ]]; then
#      if [[ (-n $JOBS) && (-z $(grep $NUTMP_FILE $JOBS)) ]]; then
#        NUTMP_LIST="$NUTMP_LIST $NUTMP_FILE"
#        echo "Removing $NUTMP_FILE ..."
#        rm -f 0-code/$NUTMP_FILE
#      fi
#    fi
    echo "Removing $FILE ..."
    rm -f $FILE;
  fi;
done

NUTMP_LIST=$(ls 0-code/nu-tmp-?????)
for FILE in $NUTMP_LIST; do
  if [[ -z $(grep $(basename $FILE) $PREFIX.o*) ]]; then
    echo "Removing executable $FILE ..."
    rm $FILE
  fi
done

