#!/bin/bash

# Copy main working directory
rsync --delete -avz $HOME/papers/sterile-nu/sim/ fnpcsrv1.fnal.gov:/grid/app/jkopp/sterile-nu \
      --exclude .git/ --exclude *genie*

# Change permissions for job execution
ssh grid chmod -R g+rX /grid/app/jkopp/sterile-nu

