#!/bin/bash
globes=$HOME/software/installed/globes-devel/bin/globes
SUFFIX=""

cd 0-code/

echo "******** Warnings in C code **************"
grep "FIXME" *
echo "******************************************"
echo


# MINOS debugging
# ---------------

# Event spectra (standard oscillations)
export GLB_PATH="glb/minos-nc"
export OSC_PARAMS="0,0,0.7854,0,0,2.32e-3"
#export OSC_PARAMS="0,0,0.0,0,0,2.43e-3"
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 1 minos-nc.glb > ../1-spectra/minos-nc-near$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 0 minos-nc.glb > ../1-spectra/minos-nc-far$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 1 minos-cc.glb > ../1-spectra/minos-cc-near$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 0 minos-cc.glb > ../1-spectra/minos-cc-far$SUFFIX.dat &
unset OSC_PARAMS

# NC event rates w/o efficiencies (used for computing efficiencies)
export OSC_PARAMS="0,0,0.0,0,0,2.43e-3"
#$globes -p $OSC_PARAMS -c3 -s -S -m minos-cc-far.glb > ../1-spectra/minos-cc-far-NCnoeff.dat &
unset OSC_PARAMS

# Event spectra (including th13 or sterile oscillations)
#./nu -a SPECTRUM -t "DM31=2.35e-3,TH13=0.2,DELTA_0=3.14159"   -e MINOS_NC > \
#  ../1-spectra/minos-th13$SUFFIX.dat
#./nu -a SPECTRUM -t "DM31=2.35e-3,TH13=0.0,DM41=0.5,TH24=0.2" -e MINOS_NC > \
#  ../1-spectra/minos-th24$SUFFIX.dat
#./nu -a SPECTRUM -t "DM31=2.35e-3,TH13=0.0,DM41=0.5,TH34=0.9" -e MINOS_NC > \
#  ../1-spectra/minos-th34$SUFFIX.dat

# Thomas' best fit point
#./nu -a SPECTRUM -t "DM31=2.35e-3,TH13=0.0,TH15=0.115255,TH25=0.14344,TH14=0.13226,TH24=0.1764,DM41=0.47,DM51=0.93" -e MINOS_NC > ../1-spectra/minos-bf-thomas$SUFFIX.dat

# Standard model fit of atmospheric parameters
./nu -e MINOS_CC -a PARAM_SCAN -p "TH23,0.55,1.05,20" -p "DM31,0.0015,0.0035,20" \
      > ../2-smparams/th23dm31-minos$SUFFIX.dat

# Fits of sterile neutrino models to MINOS data (to compare to plots from 1001.0336)
#./nu -f 4 -e MINOS_NC -a PARAM_SCAN \
#    -t "TH12=0.0,DM21=0.0,TH13=0.0,DM41=0.5" -m "DM31" \
#    -p "TH23,0.5236,1.0472,10" \
#    -p "TH34,0,1.2217,10" \
#    -p "TH24,0,0.20944,6" > ../3-3p1/th23th34th24-minos-th13-0$SUFFIX.dat &
#./nu -f 4 -e MINOS_NC -a PARAM_SCAN \
#    -t "TH12=0.0,DM21=0.0,DELTA_0=4.71239,TH13=0.2094395,DM41=0.5" -m "DM31" \
#    -p "TH23,0.5236,1.0472,10" \
#    -p "TH34,0,1.2217,10" \
#    -p "TH24,0,0.20944,6" > ../3-3p1/th23th34th24-minos-th13-12deg$SUFFIX.dat &


# Atmospherics debugging
# ----------------------
#./nu -a PARAM_SCAN -e ATM_COMP -p "Um4,0,0.5,20" -p "Um5,0,0.5,20" \
#     -m "TH23,TH34,TH35,DM31" > ../6-atm/Um4Um5$SUFFIX.dat &


# Constraints on the standard oscillation parameters in sterile neutrino models
# -----------------------------------------------------------------------------

# 4 flavors, all experiments
export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
         -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01" \
         -p "DM41,-1,1,5,LOGSCALE" -m "DM41,TH14,TH24,TH34,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=8
#OUT_FILE=th23dm31-4f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,20"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-4f-all$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,28,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,20"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-4f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,28,LOGSCALE" -m "DM31" $SCAN_PARAMS

# 5 flavors, all experiments
export SCAN_PARAMS="-v -f 5 -a PARAM_SCAN \
         -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01" \
         -p "DM41,-1,1,5,LOGSCALE"    -p "DM51,-1,1,5,LOGSCALE" \
         -m "DM41,DM51,TH14,TH24,TH15,TH25,TH34,TH35,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=16
#OUT_FILE=th23dm31-5f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-5f-all$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,14,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-5f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,14,LOGSCALE" -m "DM31" $SCAN_PARAMS

# 5 flavors, only experiments w/o evidence for sterile neutrinos
export SCAN_PARAMS="-v -f 5 -a PARAM_SCAN \
         -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01" \
         -p "DM41,-1,1,5,LOGSCALE"    -p "DM51,-1,1,5,LOGSCALE" \
         -m "DM41,DM51,TH14,TH24,TH15,TH25,TH34,TH35,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=16
#OUT_FILE=th23dm31-5f-nevid$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-5f-nevid$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,14,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-5f-nevid$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,14,LOGSCALE" -m "DM31" $SCAN_PARAMS

# And now the same for 3 flavors only
export SCAN_PARAMS="-v -f 3 -a PARAM_SCAN -e SBL -e ATM_COMP -e MINOS_NC -m "DELTA_0" "
#./nu -p "TH23,0.4,1.1,20"          -p "DM31,1.5e-3,3.5e-3,10"    -m "TH13" $SCAN_PARAMS \
#     > ../2-smparams/th23dm31-3f-all$SUFFIX.dat &
#./nu -p "TH13,-2,-0.6,14,LOGSCALE" -p "DM31,1.5e-3,3.5e-3,10"    -m "TH23" $SCAN_PARAMS \
#     > ../2-smparams/th13dm31-3f-all$SUFFIX.dat &
#./nu -p "TH23,0.4,1.1,20"          -p "TH13,-2,-0.6,14,LOGSCALE" -m "DM31" $SCAN_PARAMS \
#     > ../2-smparams/th23th13-3f-all$SUFFIX.dat &
unset NU_SIZE
unset SCAN_PARAMS


# dm41--dm51 plots
# ----------------

export SCAN_PARAMS="-v -a PARAM_SCAN \
         -p "DM41,-1,1,80,LOGSCALE"         -p "DM51,-1,1,80,LOGSCALE" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -s "TH34,-1.5,-0.3,2,LOGSCALE"     -s "TH35,-1.5,-0.3,2,LOGSCALE" \
         -m "TH14,TH24,TH15,TH25,TH34,TH35,TH23,DM31,TH13,DELTA_0,DELTA_1,DELTA_2" "
# Atm. + MINOS
#NU_SIZE=16 OUT_FILE=dm41dm51-atm-minos$SUFFIX.dat \
#  ./nu-batch -e ATM_COMP -e MINOS_NC $SCAN_PARAMS

# All experiments *except* MINOS
#NU_SIZE=8  OUT_FILE=dm41dm51-sbl-atm$SUFFIX.dat \
#  ./nu-batch -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP $SCAN_PARAMS

# Complete fit to all implemented experiments
#NU_SIZE=32 OUT_FILE=dm41dm51-all$SUFFIX.dat \
#  ./nu-batch -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC $SCAN_PARAMS
unset SCAN_PARAMS


# th14-th24-dm41 plots
# --------------------

export SCAN_PARAMS="-f 4 -a PARAM_SCAN \
                    -p "DM41,-1.8,1.8,36,LOGSCALE" \
                    -p "TH14,-3,-0.2,28,LOGSCALE" \
                    -p "TH24,-3,-0.2,28,LOGSCALE""
#./nu -e LSND       $SCAN_PARAMS > ../3-3p1/dm41th14th24-lsnd$SUFFIX.dat &
#./nu -e LSND-C12   $SCAN_PARAMS > ../3-3p1/dm41th14th24-lsnd-c12$SUFFIX.dat &
#./nu -e MB         $SCAN_PARAMS > ../3-3p1/dm41th14th24-mb$SUFFIX.dat &
#./nu -e MBANTI     $SCAN_PARAMS > ../3-3p1/dm41th14th24-mbanti$SUFFIX.dat &
#./nu -e SBL        $SCAN_PARAMS > ../3-3p1/dm41th14th24-sbl$SUFFIX.dat &
#./nu -e KARMEN     $SCAN_PARAMS > ../3-3p1/dm41th14th24-karmen$SUFFIX.dat &
#./nu -e KARMEN-C12 $SCAN_PARAMS > ../3-3p1/dm41th14th24-karmen-c12$SUFFIX.dat &
#./nu -e NOMAD      $SCAN_PARAMS > ../3-3p1/dm41th14th24-nomad$SUFFIX.dat &
#./nu -e CDHS       $SCAN_PARAMS > ../3-3p1/dm41th14th24-cdhs$SUFFIX.dat &
#./nu -e ATM_COMP -m "TH34" $SCAN_PARAMS > ../3-3p1/dm41th14th24-atm$SUFFIX.dat &
#./nu -e MINOS_NC -m "TH34" $SCAN_PARAMS > ../3-3p1/dm41th14th24-minos$SUFFIX.dat &
#./nu -e E776       $SCAN_PARAMS > ../3-3p1/dm41th14th24-e776$SUFFIX.dat &

#./nu -e LSND -e MBANTI $SCAN_PARAMS > ../3-3p1/dm41th14th24-lsnd-mbanti$SUFFIX.dat &
#./nu -e KARMEN -e NOMAD -e MB -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-nevid-app$SUFFIX.dat &
#./nu -e SBL -e CDHS -e ATM_COMP -e MINOS_NC -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-nevid-disapp$SUFFIX.dat &
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -e MINOS_NC -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-nevid$SUFFIX.dat &
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-nevid-nominos$SUFFIX.dat &
#./nu -e SBL -e CDHS -e ATM_COMP -e MINOS_NC -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-disapp$SUFFIX.dat &

export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
                    -p "DM41,-1.8,1.8,72,LOGSCALE" \
                    -p "TH14,-2.5,-0.2,23,LOGSCALE" \
                    -p "TH24,-2.5,-0.2,23,LOGSCALE""
#./nu -e NOMAD -e KARMEN -e MB -e MBANTI -e LSND -m "TH34" \
#                 $SCAN_PARAMS > ../3-3p1/dm41th14th24-app$SUFFIX.dat &
unset SCAN_PARAMS



# Um4--Ut4 plots
# --------------

export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,0.45,9" -p "TH34,0.0001,0.7,14" -p "DM41,-1,1,10,LOGSCALE" \
         -m "DM41,TH14,TH23,DM31,TH13,DELTA_0,DELTA_1,DELTA_2" "
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC \
#         $SCAN_PARAMS > ../7-3p1-fits/all$SUFFIX.dat &

#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -e MINOS_NC \
#         $SCAN_PARAMS > ../7-3p1-fits/noevid$SUFFIX.dat &

export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,0.9,30" -p "TH34,0.0001,0.7,1" -p "DM41,-1,1,10,LOGSCALE" \
         -m "DM41,TH14,TH23,DM31,TH13,DELTA_0,DELTA_1,DELTA_2" "
#./nu -e SBL -e MBANTI -e LSND \
#         $SCAN_PARAMS > ../7-3p1-fits/evid$SUFFIX.dat &
unset SCAN_PARAMS


# Um4--Ut4--dm41 plots
# --------------------

export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,0.6,15" -p "TH34,0.0001,0.7,14" -p "DM41,-2,2,40,LOGSCALE" "
#./nu -e CDHS -e ATM_COMP -e MINOS_NC \
#         $SCAN_PARAMS > ../7-3p1-fits/th24th34dm41-noevid$SUFFIX.dat &

#./nu -e MINOS_NC \
#         $SCAN_PARAMS > ../7-3p1-fits/th24th34dm41-minos$SUFFIX.dat &

export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN -t "TH13=0.0" \
         -p "TH24,0.0001,0.6,60" -p "TH34,0.0001,0.7,1" -p "DM41,-1,1,40,LOGSCALE" "
#./nu -e SBL -e MBANTI -e LSND -m "TH14" \
#         $SCAN_PARAMS > ../7-3p1-fits/th24th34dm41-evid$SUFFIX.dat &
unset SCAN_PARAMS


# chi^2 at global best fit point / goodness of fit tests
# ------------------------------------------------------

# NOTE: We use non-zero starting values for active-sterile mixing angles since
# otherwise, the minimizer might never find the right region of parameter space

export BF_DIR="results/"
#export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
#         -t "TH14=1e-7,TH24=1e-7,TH34=1e-7" \
#         -p "DM41,-1,1,20,LOGSCALE" \
#         -m "TH23,DM31,TH13,DELTA_0" "
#export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
#         -t "TH14=0.01,TH24=0.01" \
#         -p "DM41,-1,1,20,LOGSCALE" \
#         -m "DM41,TH14,TH24,TH34,TH23,DM31,TH13,DELTA_0,DELTA_1,DELTA_2" "
export SCAN_PARAMS="-v -f 5 -a PARAM_SCAN \
         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01" \
         -p "DM41,-1,1,20,LOGSCALE"         -p "DM51,-1,1,20,LOGSCALE" \
         -m "DM41,DM51,TH14,TH24,TH15,TH25,TH34,TH35,TH23,DM31,TH13,DELTA_0,DELTA_1,DELTA_2" "

# All experiments
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC \
#     $SCAN_PARAMS > ../$BF_DIR/all$SUFFIX.dat &

# All experiments except MINOS (atm. computed)
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP  \
#     $SCAN_PARAMS > ../$BF_DIR/all-atmcomp$SUFFIX.dat &

# All experiments except MINOS (atm. tabulated, as in 3+2 PRL)
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_TABLE \
#     $SCAN_PARAMS > ../$BF_DIR/all-atmtab$SUFFIX.dat &


# All experiments except LSND + MB \bar\nu (experiments with no evidence for \nu_s)
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -e MINOS_NC \
#     $SCAN_PARAMS > ../$BF_DIR/noevid$SUFFIX.dat &

# All experiments except LSND + MB \bar\nu + MINOS (atm. computed)
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP \
#     $SCAN_PARAMS > ../$BF_DIR/noevid-atmcomp$SUFFIX.dat &

# All experiments except LSND + MB \bar\nu + MINOS (atm. tabulated)
#./nu -e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_TABLE \
#     $SCAN_PARAMS > ../$BF_DIR/noevid-atmtab$SUFFIX.dat &


# Only disappearance experiments
#./nu -e SBL -e CDHS -e ATM_COMP -e MINOS_NC \
#     $SCAN_PARAMS > ../$BF_DIR/disapp$SUFFIX.dat &

# Only disappearance experiments without MINOS (atm. computed)
#./nu -e SBL -e CDHS -e ATM_COMP \
#     $SCAN_PARAMS > ../$BF_DIR/disapp-atmcomp$SUFFIX.dat &

# Only disappearance experiments without MINOS (atm. tabulated)
#./nu -e SBL -e CDHS -e ATM_TABLE \
#     $SCAN_PARAMS > ../$BF_DIR/disapp-atmtab$SUFFIX.dat &


# LSND + MB \bar\nu (experiments that have evidence for \nu_s)
#./nu -e MBANTI -e LSND \
#     $SCAN_PARAMS > ../$BF_DIR/evid$SUFFIX.dat &


# Only appearance experiments
#./nu -e NOMAD -e KARMEN -e MB -e MBANTI -e LSND \
#     $SCAN_PARAMS > ../$BF_DIR/app$SUFFIX.dat &


# Only appearance experiments without evidence for sterile neutrinos
#./nu -e NOMAD -e KARMEN -e MB \
#     $SCAN_PARAMS > ../$BF_DIR/noevid-app$SUFFIX.dat &


# Switching off one experiment at a time
#EXPS="SBL KARMEN NOMAD CDHS MB MBANTI LSND ATM_COMP MINOS_NC"
#ALL_EXPS="-e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e MBANTI -e LSND -e ATM_COMP -e MINOS_NC "
#EVID="-e MBANTI -e LSND "
#NEVID="-e SBL -e KARMEN -e NOMAD -e CDHS -e MB -e ATM_COMP -e MINOS_NC "
#APP="-e KARMEN -e NOMAD -e MB -e MBANTI -e LSND "
#DISAPP="-e SBL -e CDHS -e ATM_COMP -e MINOS_NC "
#for THIS_EXP in $EXPS; do
#  echo "Run without $THIS_EXP ..."
#  ./nu ${ALL_EXPS/"-e $THIS_EXP "/} $SCAN_PARAMS > ../$BF_DIR/no-$THIS_EXP-all$SUFFIX.dat &
#  ./nu ${EVID/"-e $THIS_EXP "/}     $SCAN_PARAMS > ../$BF_DIR/no-$THIS_EXP-evid$SUFFIX.dat &
#  ./nu ${NEVID/"-e $THIS_EXP "/}    $SCAN_PARAMS > ../$BF_DIR/no-$THIS_EXP-nevid$SUFFIX.dat &
#  ./nu ${APP/"-e $THIS_EXP "/}      $SCAN_PARAMS > ../$BF_DIR/no-$THIS_EXP-app$SUFFIX.dat &
#  ./nu ${DISAPP/"-e $THIS_EXP "/}   $SCAN_PARAMS > ../$BF_DIR/no-$THIS_EXP-disapp$SUFFIX.dat
#done

unset SCAN_PARAMS

