#!/bin/bash
globes=$HOME/papers/sterile-nu/globes/bin/globes
SUFFIX=""

cd 0-code/

echo "******** Warnings in C code **************"
grep "FIXME" *
echo "******************************************"
grep "FIXME" $(find glb/* -name "*.glb")
echo "******************************************"
#echo

# ---------------------------------------------------------------------------
#                   Debugging and testing codes
# ---------------------------------------------------------------------------

# ICARUS debugging / testing
# --------------------------

# 4-flavor fit
export SP="-f 4 -a PARAM_SCAN --no-ih \
           -t "TH13=0.156" -t "TH24=0.4" \
           -p "s22thmue,-4.01,-1.01,30,LOGSCALE" \
           -p "DM41,-2.0,2.0,40,LOGSCALE""
#./nu $SP -e ICARUS-2012  >  ../9-devel/icarus-2012-test.dat
#./nu $SP -e ICARUS-2014  >  ../9-devel/icarus-2014-test.dat

# 2-flavor fit to reproduce the official ICARUS result
export SP="-f 4 -a PARAM_SCAN --no-ih \
           -t "TH13=0,TH23=0,TH14=0,TH24=0,TH34=0,DM41=1,M4_GAMMA=1e-30,MA_OVER_M4=0.1" \
           -p "TH12,-4.01,-1.01,30,LOGSCALE" \
           -p "DM21,-2.0,2.0,40,LOGSCALE""
unbuffer ./nu $SP -e ICARUS-2014  | tee  ../9-devel/icarus-2014-test.dat
unset SP


# T2K debugging / testing
# -----------------------

#export SP="-a SPECTRUM -e T2K"
#./nu $SP -t "TH12=0,TH23=0,TH13=0,DM21=0" \
#  > ../9-devel/t2k-spectrum-no-osc.dat
#./nu $SP -t "TH23=0.809407,TH13=0.206401,DM31=2.591e-3,DELTA_0=1.91" \
#  > ../9-devel/t2k-spectrum-osc.dat
#unset SP

# 3-flavor fits
#export SP="-f 3 -e T2K -a PARAM_SCAN -m "TH13,DELTA_0" \
#           -s "DELTA_0,0,6.28,8" \
#           -p "TH23,0.55,1.0,18" \
#           -p "DM31,2e-3,3e-3,20""
#./nu $SP > ../9-devel/t2k-3f-th23dm31.dat &
#
#export SP="-f 3 -e T2K -a PARAM_SCAN -m "TH23,DELTA_0" \
#           -s "DELTA_0,0,6.28,8" \
#           -p "TH13,0,0.1,10" \
#           -p "DM31,2e-3,3e-3,20""
#./nu $SP > ../9-devel/t2k-3f-th13dm31.dat &
#
#export SP="-f 3 -e T2K -a PARAM_SCAN -m "TH23,DM31" \
#           -p "TH13,0,0.3,10" \
#           -p "DELTA_0,0,6.28,8""
#./nu $SP > ../9-devel/t2k-3f-th13delta.dat &
#
#export SP="-f 3 -e T2K -a PARAM_SCAN -m "DM31,DELTA_0" \
#           -s "DELTA_0,0,6.28,16" \
#           -s "DM31,2e-3,3e-3,10" \
#           -p "TH23,0.55,1.0,18" \
#           -p "TH13,0,0.3,20""
#./nu $SP > ../9-devel/t2k-3f-th23th13.dat &
#unset SP

# 4-flavor fits
#OUT_FILE=th24dm41-t2k$SUFFIX.dat ./compile-and-run -l \
#    -f 4 -e T2K -a PARAM_SCAN \
#    -m "TH23,DM31" \
#    -t "TH23=0.925,DM31=0.00245" \
#    -p "TH24,0,0.36,9" \
#    -p "DM41,-4,3,28,LOGSCALE" &


# MINOS debugging / testing (based on official data release)
# ----------------------------------------------------------

# 3+1 fit
#OUT_FILE=th24dm41-minos-2017$SUFFIX.dat ./compile-and-run -l \
#    -f 4 -e MINOS_2017 -a PARAM_SCAN \
#    -t "TH23=0.925,DM31=0.00245" \
#    -m "TH23,DM31,TH34" \
#    -p "TH24,0,0.35,35" \
#    -p "DM41,-4,3,56,LOGSCALE"


# MINOS debugging / testing (old GLoBES-based code)
# -------------------------------------------------

export GLB_PATH="glb/minos-2016"

# Event spectra (standard oscillations)
export OSC_PARAMS="0.587,0.149,0.695,0,7.54e-5,2.445e-3"
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 1 minos-nc.glb > ../1-spectra/minos-nc-near$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 0 minos-nc.glb > ../1-spectra/minos-nc-far$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 1 minos-cc.glb > ../1-spectra/minos-cc-near$SUFFIX.dat &
#$globes -p $OSC_PARAMS -r0 -s -S -m -e 0 minos-cc.glb > ../1-spectra/minos-cc-far$SUFFIX.dat &
#$globes -N -r0 -s -S -m -e 0 minos-cc.glb > ../1-spectra/minos-cc-far-noosc$SUFFIX.dat &
unset OSC_PARAMS

# Event spectra (3+1)
export SP="-a SPECTRUM -e MINOS_NC_2016 \
           -t TH12=0.587,TH13=0.149,TH23=0.695,DELTA_0=0,DM21=7.54e-5,DM31=2.445e-3 \
           -t TH24=0.17,DM41=1.0"
#./nu $SP > ../9-devel/minos-spectrum.dat
unset SP

# Standard model fit of atmospheric parameters (MINOS CC only)
#./nu -e MINOS_CC_2016 -a PARAM_SCAN -t "TH13=0.,TH12=0.,DM21=0." \
#     -p "TH23,0.55,1.05,20" -p "DM31,0.0015,0.0035,40" \
#     > ../2-smparams/th23dm31-minos$SUFFIX.dat # &
#./nu -e MINOS_NC_2016 -a PARAM_SCAN -t "TH13=0." \
#     -p "TH23,0.55,1.05,20" -p "DM31,0.0015,0.0035,40" \
#     > ../2-smparams/th23dm31-minos-ccnc$SUFFIX.dat &

# 3+1 fit
#OUT_FILE=th24dm41-minos$SUFFIX.dat ./compile-and-run -l \
#    -f 4 -e MINOS_NC_2016 -a PARAM_SCAN \
#    -t "TH23=0.925,DM31=0.00245" \
#    -m "TH23,DM31,TH34" \
#    -p "TH24,0,0.35,35" \
#    -p "DM41,-4,3,56,LOGSCALE"


# Daya Bay testing
# ----------------
#OUT_FILE=th13dm31-db-sterile$SUFFIX.dat SBLDEFS="DB" \
#  ./compile-and-run -l -f 3 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH13,0.1,0.2,20" \
#                    -p "DM31,2e-3,3e-3,20"
#OUT_FILE=th13dm31-db-3f$SUFFIX.dat SBLDEFS="DB_3F" \
#  ./compile-and-run -l -f 3 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH13,0.1,0.2,20" \
#                    -p "DM31,2e-3,3e-3,20"

#OUT_FILE=th14dm41-db-sterile$SUFFIX.dat SBLDEFS="DB" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -m "TH13,DM31" \
#                    -p "TH14,0,0.6,20" \
#                    -p "DM41,-3.0,1.4,88,LOGSCALE"
#OUT_FILE=th14dm41-db-3f$SUFFIX.dat SBLDEFS="DB_3F" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -m "TH13,DM31" \
#                    -p "TH14,0,0.6,20" \
#                    -p "DM41,-3.0,1.4,88,LOGSCALE"

# Double Chooz testing
# --------------------
#OUT_FILE=th13dm31-dc$SUFFIX.dat SBLDEFS="DC" \
#  ./compile-and-run -l -f 3 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH13,0.02,0.5,200" \
#                    -p "DM31,1e-3,4e-3,300"
#OUT_FILE=th13chi2-dc$SUFFIX.dat SBLDEFS="DC" \
#  ./compile-and-run -l -f 3 --no-ih -a PARAM_SCAN -e SBL \
#                    -m DM31 -c DM31 -t DM31=0.00241 \
#                    -p "TH13,0.02,0.5,1000"
#OUT_FILE=th14dm41-dc$SUFFIX.dat SBLDEFS="DC" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -m "TH13,DM31" \
#                    -p "TH14,0,0.8,20" \
#                    -p "DM41,-1.5,1.5,60,LOGSCALE"

# DANSS testing
# -------------
#OUT_FILE=th14dm41-danss$SUFFIX.dat SBLDEFS="DANSS" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH14,0,0.8,20" \
#                    -p "DM41,-2,1,30,LOGSCALE"


# NEOS testing
# -------------
#OUT_FILE=th14dm41-neos$SUFFIX.dat SBLDEFS="NEOS" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH14,0,0.8,20" \
#                    -p "DM41,-2,1,30,LOGSCALE"


# Testing of Alvaro's codes
# -------------------------
#OUT_FILE=th14dm41-db-neos$SUFFIX.dat SBLDEFS="DB_NEOS_ALVARO" \
#  ./compile-and-run -l -f 4 --no-ih -a PARAM_SCAN -e SBL\
#                    -p "TH14,0,0.8,20" \
#                    -p "DM41,-2,1,30,LOGSCALE"


# ---------------------------------------------------------------------------
#                             Production Runs
# ---------------------------------------------------------------------------

export SP="-f 4 -a PARAM_SCAN \
           -m "DELTA_0" -s "DELTA_0,0.,6.283185,4" \
           -p "DM41,-1.8,1.8,36,LOGSCALE" \
           -p "s22thmue,-4.01,-0.01,20,LOGSCALE" \
           -p "Um4,-2.1,-0.1,20,LOGSCALE""
#OUT_FILE="dm41thmeUm4-icarus-2014$SUFFIX.dat"  ./compile-and-run -l -e ICARUS-2014 $SP
#OUT_FILE="dm41thmeUm4-opera-2013$SUFFIX.dat"   ./compile-and-run -l -e OPERA       $SP
unset SP


# \nu_e disappearance constraints
# -------------------------------

export SP="-f 4 --no-ih -a PARAM_SCAN \
                    -p "DM41,-1.4,1.4,56,LOGSCALE" \
                    -p "TH13,0,0.3,10" \
                    -p "TH14,0,0.6,20" "
#OUT_FILE=dm41th13th14-sblreactors$SUFFIX.dat SBLDEFS="SBL BUGEY_SP" \
#  ./compile-and-run -l $SP -e SBL
#OUT_FILE=dm41th13th14-sbllblreactors$SUFFIX.dat SBLDEFS="SBL BUGEY_SP CHOOZ PV DC DB RENO" \
#  ./compile-and-run -l $SP -e SBL
#OUT_FILE=dm41th13th14-lblreactors$SUFFIX.dat SBLDEFS="CHOOZ PV DC DB RENO" \
#  ./compile-and-run -l $SP -e SBL -c DM31
#OUT_FILE=dm41th13th14-gal$SUFFIX.dat SBLDEFS="GAL" \
#  ./compile-and-run -l $SP -e SBL
#OUT_FILE=dm41th13th14-c12$SUFFIX.dat SBLDEFS="" \
#  ./compile-and-run -l $SP -e C12

export NU_SIZE=32
export SP="$SP -s "DELTA_0,0,4.7,3" -s "DELTA_1,0,4.7,3" -m "DELTA_0,DELTA_1""
#OUT_FILE=dm41th13th14-solar-kaml$SUFFIX.dat SBLDEFS="KAML" \
#  ./compile-and-run -l $SP -e SBL -e SOLAR -m "TH12,TH24,TH34"
#OUT_FILE=dm41th13th14-disapp-e$SUFFIX.dat SBLDEFS="SBL CHOOZ PV DC DB RENO BUGEY_SP GAL KAML"
#  ./compile-and-run -l $SP -e SBL -e SOLAR -e C12  -m "TH12,TH24,TH34"
unset NU_SIZE
unset SP





# ---------------------------------------------------------------------------
#                       4-flavor fits
# ---------------------------------------------------------------------------

# th14-th24-dm41 plots
# --------------------

# --- Separate fits to individual experiments ---
export SP="-f 4 -a PARAM_SCAN \
           -p "DM41,-1.8,1.8,72,LOGSCALE" \
           -p "TH14,-4,-0.2,39,LOGSCALE" \
           -p "TH24,-4,-0.2,39,LOGSCALE""
export S="dm41th14th24"
#./nu -e CDHS       $SP > ../3-3p1/$S-cdhs$SUFFIX.dat &
#./nu -e ATM_COMP -m "TH34" $SP > ../3-3p1/$S-atm$SUFFIX.dat &
#./nu -e MINOS_NC -m "TH34" $SP > ../3-3p1/$S-minos$SUFFIX.dat &
#./nu -e C12        $SP > ../3-3p1/$S-c12$SUFFIX.dat &
#./nu -e LSND-C12   $SP > ../3-3p1/$S-lsnd-c12$SUFFIX.dat &
#./nu -e KARMEN-C12 $SP > ../3-3p1/$S-karmen-c12-JR$SUFFIX.dat &

export SP="-f 4 -a PARAM_SCAN --no-ih \
           -p "DM41,-1.8,1.8,36,LOGSCALE" \
           -p "s22thmue,-4.01,-0.01,80,LOGSCALE" \
           -p "Um4,-2.1,-0.1,20,LOGSCALE""
export S="dm41thmeUm4"
#./nu -e LSND       $SP > ../3-3p1/$S-lsnd$SUFFIX.dat &
#./nu -e KARMEN     $SP > ../3-3p1/$S-karmen$SUFFIX.dat &
#./nu -e NOMAD      $SP > ../3-3p1/$S-nomad$SUFFIX.dat &
#./nu -e E776       $SP > ../3-3p1/$S-e776$SUFFIX.dat &
export NU_SIZE=8
#OUT_FILE=$S-e776$SUFFIX.dat ./compile-and-run $SP -e E776 -c DM31 
#OUT_FILE=$S-e776-reactors$SUFFIX.dat SBLDEFS="CHOOZ PV DC DB RENO" \
#  ./compile-and-run $SP -e E776 -e SBL -c DM31 
    # Use constraint from LBL reactors to avoid too large BG oscillations
#OUT_FILE=$S-lblreactors$SUFFIX.dat SBLDEFS="CHOOZ PV DC DB RENO" \
#  ./compile-and-run $SP -e SBL -c DM31 
unset NU_SIZE

# --- MiniBooNE ---
export SP="-e MBall200 -f 4 -a PARAM_SCAN \
           -p "DM41,-1.8,1.8,36,LOGSCALE" \
           -p "s22thmue,-4.01,-0.01,40,LOGSCALE" \
           -p "Um4,-2.1,-0.1,20,LOGSCALE""
export S="dm41thmeUm4-mb200"
#export SP="-e MBall200 -f 4 -a PARAM_SCAN \
#           -p "DM41,-1.8,1.8,36,LOGSCALE" \
#           -p "TH14,-2,-0.1,19,LOGSCALE" \
#           -p "TH24,-2,-0.1,19,LOGSCALE""
#export S="dm41th14th24-mb200"
export MBALL="NU_APP NUBAR_APP COMBINED_APP NU_DISAPP NUBAR_DISAPP"
#OUT_FILE=$S-nu-app$SUFFIX.dat       MBDEFS="NU_APP"       ./compile-and-run $SP
#OUT_FILE=$S-nu-disapp$SUFFIX.dat    MBDEFS="NU_DISAPP"    ./compile-and-run $SP
#OUT_FILE=$S-nubar-app$SUFFIX.dat    MBDEFS="NUBAR_APP"    ./compile-and-run $SP
#OUT_FILE=$S-nubar-disapp$SUFFIX.dat MBDEFS="NUBAR_DISAPP" ./compile-and-run $SP
#OUT_FILE=$S-combi-app$SUFFIX.dat    MBDEFS="NU_APP NUBAR_APP COMBINED_APP" ./compile-and-run $SP
#OUT_FILE=$S-combi-disapp$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP"        ./compile-and-run $SP
#OUT_FILE=$S-all$SUFFIX.dat          MBDEFS=$MBALL         ./compile-and-run $SP
#
#OUT_FILE=$S-nu-app-full$SUFFIX.dat       MBDEFS="NU_APP FULL_OSC"       ./compile-and-run $SP
#OUT_FILE=$S-nu-disapp-full$SUFFIX.dat    MBDEFS="NU_DISAPP FULL_OSC"    ./compile-and-run $SP
#OUT_FILE=$S-nubar-app-full$SUFFIX.dat    MBDEFS="NUBAR_APP FULL_OSC"    ./compile-and-run $SP
#OUT_FILE=$S-nubar-disapp-full$SUFFIX.dat MBDEFS="NUBAR_DISAPP FULL_OSC" ./compile-and-run $SP
#OUT_FILE=$S-combi-app-full$SUFFIX.dat    MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" ./compile-and-run $SP
#OUT_FILE=$S-combi-disapp-full$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC"        ./compile-and-run $SP
#OUT_FILE=$S-all-full$SUFFIX.dat          MBDEFS="$MBALL FULL_OSC"       ./compile-and-run $SP
unset SP
unset S

# Simplified or specialized fits to individual experiments
#OUT_FILE="dm41th14th24-icarus$SUFFIX.dat"  qsub nu-batch  -v -f 4 -a PARAM_SCAN -e ICARUS-2012 \
#     -m "DELTA_0" -s "DELTA_0,0.,6.283185,4" \
#     -p "DM41,-1.8,1.8,72,LOGSCALE" \
#     -p "TH14,-4,-0.2,39,LOGSCALE" \
#     -p "TH24,-4,-0.2,39,LOGSCALE"
#OUT_FILE="dm41thmeUm4-icarus$SUFFIX.dat"  qsub nu-batch  -v -f 4 -a PARAM_SCAN -e ICARUS \
#     -m "DELTA_0" -s "DELTA_0,0.,6.283185,4" \
#     -p "DM41,-1.8,1.8,36,LOGSCALE" \
#     -p "s22thmue,-4.01,-0.01,40,LOGSCALE" \
#     -p "Um4,-2.1,-0.1,40,LOGSCALE"
#OUT_FILE="delta0delta1-icarus-test3$SUFFIX.dat" qsub nu-batch -v -f 4 -a PARAM_SCAN -e ICARUS \
#      -p "DELTA_0,0,6.28,32" \
#      -p "DELTA_1,0,6.28,32" \
#      -t "DM41=10.0,s22thmue=0.2,Um4=0.6,DM21=0.0,TH34=0.2"

#OUT_FILE="delta0delta1-minos$SUFFIX.dat" qsub nu-batch -v -f 4 -a PARAM_SCAN -e MINOS_NC \
#      -p "DELTA_0,0,6.28,16" \
#      -p "DELTA_1,0,6.28,16" \
#      -t "DM41=1.0,s22thmue=0.1,Um4=0.4,DM21=0.0,TH34=0.2"
#./nu -e E776 -f 3 -a PARAM_SCAN -t "TH23=0.,DM31=0.,TH12=0." -p "DM21,-1.8,1.8,36,LOGSCALE" \
#             -p "TH12,-3,-0.2,28,LOGSCALE" > ../3-3p1/e776-2flavor$SUFFIX.dat &
#./nu -e LSND-C12 -f 3 -a PARAM_SCAN -t "TH23=0.,DM31=0.,TH12=0." -p "DM21,-1.8,1.8,72,LOGSCALE" \
#             -p "TH12,-3,-0.2,56,LOGSCALE" > ../3-3p1/lsnd-c12-2flavor$SUFFIX.dat &
#./nu -e KARMEN-C12 -f 3 -a PARAM_SCAN -t "TH23=0.,DM31=0.,TH12=0." -p "DM21,-1.8,1.8,72,LOGSCALE" \
#             -p "TH12,-3,-0.2,56,LOGSCALE" > ../3-3p1/karmen-c12-2flavor-JR$SUFFIX.dat &
#./nu -e SBL -f 4 -a PARAM_SCAN -p "DM41,-1.,1.,100,LOGSCALE" \
#                               -p "TH14,-3,-0.2,100,LOGSCALE" \
#                               -p "TH24,0.1,0.1,1" > ../3-3p1/dm41th14th24-sbl.dat &
#./nu -e SOLAR -f 3 -a PARAM_SCAN -p "TH12,0.3,0.75,20" \
#                                 -p "DM21,1e-5,20e-5,19" > ../7-3flavor/solar.dat &


# --- Combined fits ---
# - NOTE: Changing the order of the scan (th14, th24, dm41 instead of dm41, th14, th23
#   could reduce the number of times the solar probabilities have to be re-evaluated
### - NOTE: Fix *delta_CP ~ 1.3* since this gives the most conservative results
###   for ICARUS (???)
export SP="-v -f 4 -a PARAM_SCAN \
           -p "DM41,-1.4,1.4,56,LOGSCALE" \
           -p "s22thmue,-4.01,-0.01,40,LOGSCALE" \
           -p "Um4,-2.1,-0.1,20,LOGSCALE" \
           -t "DELTA_0=1.3" "
export SP2="-s "DELTA_0,0,4.7,3" -s "DELTA_1,0,4.7,3" -m "DELTA_0,DELTA_1""
export NU_SIZE=64
#OUT_FILE=dm41th14th24-lsnd-mbapp$SUFFIX.dat   MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run  $SP  -e MBall200 -e LSND

#OUT_FILE=dm41th14th24-evid$SUFFIX.dat         MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run $SP  -e LSND -e MBall200 -e SBL --best-fit
#OUT_FILE=dm41th14th24-nevid$SUFFIX.dat        MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP $SP2 -m "TH12"  -e ICARUS -e KARMEN -e NOMAD -e E776 -e C12 \
#                                         -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200
#OUT_FILE=dm41th14th24-nevid-app$SUFFIX.dat \
#  ./compile-and-run  $SP  -e ICARUS -e KARMEN -e NOMAD -e E776
#OUT_FILE=dm41th14th24-nevid-disapp$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP $SP2 -m "TH12" -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200

#OUT_FILE=dm41th14th24-disapp$SUFFIX.dat       MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP $SP2  -m "TH12" -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200
#OUT_FILE=dm41th14th24-app$SUFFIX.dat          MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run  $SP $SP2 -e ICARUS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND
unset NU_SIZE

#./nu -e KARMEN -e NOMAD -e MBall200 -e LSND \
#                 $SP -m "TH34" > ../3-3p1/dm41th14th24-app-GL$SUFFIX.dat &
#./nu -e SBL -e C12 -e CDHS -e ATM_COMP -e MINOS_NC \
#                 $SP -m "TH34" > ../3-3p1/dm41th14th24-disapp-GL$SUFFIX.dat &
#./nu -e LSND -e MBall200 \
#                  $SP > ../3-3p1/dm41th14th24-lsnd-mb$SUFFIX.dat &

#OUT_FILE=dm41th14th24-c12-e$SUFFIX.dat  ./compile-and-run  -e C12 \
#  -f 4 -a PARAM_SCAN --no-ih    -p "DM41,-1.8,1.8,36,LOGSCALE" \
#  -p "TH14,-2,-0.1,19,LOGSCALE" -p "TH24,-2,-0.1,1,LOGSCALE"
#OUT_FILE=dm41th14th24-disapp-e$SUFFIX.dat  ./compile-and-run  -e C12 -e SBL \
#  -f 4 -a PARAM_SCAN --no-ih    -p "DM41,-1.8,1.8,36,LOGSCALE" \
#  -p "TH14,-2,-0.1,19,LOGSCALE" -p "TH24,-2,-0.1,1,LOGSCALE"
#OUT_FILE=dm41th14th24-disapp-mu$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  -e ATM -e MINOS_NC -e CDHS -e MBall200 \
#  -f 4 -a PARAM_SCAN --no-ih    -p "DM41,-1.8,1.8,36,LOGSCALE" \
#  -p "TH14,-2,-0.1,1,LOGSCALE"  -p "TH24,-2,-0.1,19,LOGSCALE"

unset SP
unset SP2


# Find best fit points
# --------------------

export SCAN_PARAMS="-f 4 -a PARAM_SCAN \
                    -s "DM41,-1.8,1.8,18,LOGSCALE" \
                    -s "TH14,-4,-0.2,10,LOGSCALE" \
                    -s "TH24,-4,-0.2,10,LOGSCALE" \
                    -m "TH14,TH24,DM41" "
#./nu -e MB300     $SCAN_PARAMS
#./nu -e MBanti200 $SCAN_PARAMS
#./nu -e MBall     $SCAN_PARAMS
unset SCAN_PARAMS


# \nu_\mu disappearance constraints
# ---------------------------------

export SP="-f 4 -a PARAM_SCAN \
           -t "TH14=1e-7,TH24=1e-7,TH34=1e-7" -m "DM31,TH34"\
           -p "DM41,-1.4,1.4,56,LOGSCALE" \
           -p "TH23,0.3,1.25,19" \
           -p "TH24,0.0001,0.6,20" "
export SP2="-s "DELTA_0,0,4.7,3" -s "DELTA_1,0,4.7,3" -m "DELTA_0,DELTA_1""
#OUT_FILE=dm41th23th24-cdhs$SUFFIX.dat    ./compile-and-run -e CDHS     $SP
#OUT_FILE=dm41th23th24-atm$SUFFIX.dat     ./compile-and-run -e ATM      $SP
export NU_SIZE=50
#OUT_FILE=dm41th23th24-minos$SUFFIX.dat   ./compile-and-run -e MINOS_NC $SP $SP2
#OUT_FILE=dm41th23th24-noevid$SUFFIX.dat   MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#                 ./compile-and-run $SP $SP2 -e CDHS -e ATM_COMP -e MINOS_NC -e MBall200
                              # Note: Solar neutrinos were found to be not competitive here
                              # and are therefore omitted (this also saves us the th12
                              # marginalization)
unset NU_SIZE

export SP="-f 4 -a PARAM_SCAN \
           -t "TH14=1e-7" \
           -p "DM41,-1.4,1.4,56,LOGSCALE" \
           -p "TH23,0.3,1.25,1" \
           -p "TH24,0.0001,0.6,20" "
#OUT_FILE=dm41th23th24-mb200dis$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#                 ./compile-and-run -e MBall200  $SP
export NU_SIZE=32
#OUT_FILE=dm41th23th24-solar$SUFFIX.dat  ./compile-and-run -e SOLAR -m "TH12,TH14,TH34"  $SP $SP2
#OUT_FILE=dm41th23th24-evid$SUFFIX.dat     MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#                 ./compile-and-run $SP -e SBL -e LSND -e MBall200 -m "TH14"
unset NU_SIZE
unset SP2
unset SP


# Um4--Ut4--dm41 plots
# --------------------

# Note: decouple electron neutrinos to allow for inclusion of sterile neutrino
# matter effects in the ATM code
#FIXME Switch back to more points (40x40x30)?
export SP="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,0.35,20" \
         -p "TH34,0.0001,1.5,20" \
         -p "DM41,-1.5,1.5,30,LOGSCALE" \
         --atm-decouple-e -t "TH12=0.,TH13=0.,TH14=0." "
#OUT_FILE=th24th34dm41-cdhs$SUFFIX.dat   ./compile-and-run -e CDHS                    $SP
#OUT_FILE=th24th34dm41-atm$SUFFIX.dat    ./compile-and-run -e ATM_COMP -m "TH23,DM31" $SP
export NU_SIZE=32
#OUT_FILE=th24th34dm41-mb-cdhs-reactors$SUFFIX.dat \
#         MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC"  SBLDEFS="CHOOZ PV DC DB RENO" \
#         ./compile-and-run $SP -e MBall200 -e CDHS -e SBL -m "TH14" -t "TH13=0.154085"
export SP="$SP -s "DELTA_0,0,4.7,3" \
               -s "DELTA_1,0,4.7,3" \
               -m "DELTA_0,DELTA_1,TH23,DM31" "
######               -s "DM31,1e-3,3e-3,2" \
######               -s "TH23,0.4,0.8,2" \
export NU_SIZE=128
#OUT_FILE=th24th34dm41-minos$SUFFIX.dat  ./compile-and-run -e MINOS_NC $SP
#OUT_FILE=th24th34dm41-noevid$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#         ./compile-and-run $SP -e CDHS -e ATM_COMP -e MINOS_NC -e MBall200
   # FIXME Include solar if possible!

export SP="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,1.5,20" \
         -p "TH34,0.0001,1.5,20" \
         -p "DM41,-1.5,1.5,1,LOGSCALE" \
         -s "DELTA_0,0,4.7,3" \
         -s "DELTA_1,0,4.7,3" \
         -m "DELTA_0,DELTA_1" "
export NU_SIZE=32
#OUT_FILE=th24th34dm41-solar$SUFFIX.dat   ./compile-and-run $SP -e SOLAR -m "TH12,TH14"
unset NU_SIZE


# MINOS plots at fixed dm^2
# (Note: Only MINOS is sensitive to the phases here -> scanning one phase is enough)
export SP="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0.0001,0.35,120" \
         -p "TH34,0.0001,1.5,120" \
         -s "DELTA_1,0,4.7,3" \
         -m "DELTA_1,TH23,DM31" "
export NU_SIZE=100
#OUT_FILE=th24th34dm41-minos-12eV2$SUFFIX.dat  ./compile-and-run $SP -e MINOS_NC \
#         -p "DM41,1.07981,1.07981,0,LOGSCALE"
#OUT_FILE=th24th34dm41-minos-1eV2$SUFFIX.dat  ./compile-and-run $SP -e MINOS_NC \
#         -p "DM41,0,0,0,LOGSCALE"
#OUT_FILE=th24th34dm41-minos-0.4eV2$SUFFIX.dat  ./compile-and-run $SP -e MINOS_NC \
#         -p "DM41,-0.39794,-0.39794,0,LOGSCALE"
#OUT_FILE=th24th34dm41-minos-0.1eV2$SUFFIX.dat  ./compile-and-run $SP -e MINOS_NC \
#         -p "DM41,-1,-1,0,LOGSCALE"
unset NU_SIZE


# Plots including scan over phases
# (Note: Only MINOS is sensitive to the phases here -> scanning one phase is enough)
export SP="-v -f 4 -a PARAM_SCAN \
         -p "TH24,0,0,0" \
         -p "Ut4,0.0001,1.0,40" \
         -p "DM41,-1.5,1.5,30,LOGSCALE" \
         -p "DELTA_0,0,0,0" \
         -p "DELTA_1,0,6.28319,8" \
         --atm-decouple-e --theta-positive -m "TH24" -t "TH12=0.,TH13=0.,TH14=0." "
#OUT_FILE=th24th34dm41-atm-phases$SUFFIX.dat    ./compile-and-run -e ATM_COMP -m "TH23,DM31" $SP
export NU_SIZE=128
#OUT_FILE=th24th34dm41-mb-cdhs-atm-phases$SUFFIX.dat  MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run $SP -e MBall200 -e CDHS -e ATM_COMP
#OUT_FILE=th24th34dm41-noevid-phases$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#         ./compile-and-run -m "TH23,DM31" $SP -e CDHS -e ATM_COMP -e MINOS_NC -e MBall200
#OUT_FILE=th24th34dm41-minos-phases$SUFFIX.dat  ./compile-and-run \
#            -e MINOS_NC -m "TH23,DM31"  $SP

############export SP="-v -f 4 -a PARAM_SCAN \
############         -p "TH24,0,0,0" \
############         -p "Ut4,0.0001,1.0,40" \
############         -p "DM41,-1.5,1.5,30,LOGSCALE" \
############         -p "DELTA_0,0,0,0" \
############         -p "DELTA_1,0,6.28319,8" \
############         --atm-decouple-e --theta-positive -m "TH24" -t "TH12=0.,TH13=0.,TH14=0." "
#############OUT_FILE=th24th34dm41-minos-phases-test$SUFFIX.dat  ./compile-and-run \
#############            -e MINOS_NC $SP
unset NU_SIZE
unset SP


# Constraints on the standard oscillation parameters in sterile neutrino models
# -----------------------------------------------------------------------------

# 4 flavors, all experiments
#FIXME Add phases!
#FIXME Include additional experiments (ICARUS!)
export SCAN_PARAMS="-v -f 4 -a PARAM_SCAN \
         -e LSND -e MBANTI200 -e SBL -e KARMEN -e NOMAD -e E776 -e C12 -e CDHS -e MB300 \
         -e ATM_COMP -e SOLAR -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01" \
         -p "DM41,-1,1,5,LOGSCALE" -m "DM41,TH14,TH24,TH34,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=16
#OUT_FILE=th23dm31-4f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,20"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-4f-all$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,28,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,20"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-4f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,28,LOGSCALE" -m "DM31" $SCAN_PARAMS

# 5 flavors, all experiments
export SCAN_PARAMS="-v -f 5 -a PARAM_SCAN \
         -e SBL -e KARMEN -e NOMAD -e CDHS -e MB300 -e MBANTI200 -e LSND -e ATM_COMP -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01" \
         -p "DM41,-1,1,5,LOGSCALE"    -p "DM51,-1,1,5,LOGSCALE" \
         -m "DM41,DM51,TH14,TH24,TH15,TH25,TH34,TH35,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=16
#OUT_FILE=th23dm31-5f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-5f-all$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,14,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-5f-all$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,14,LOGSCALE" -m "DM31" $SCAN_PARAMS

# 5 flavors, only experiments w/o evidence for sterile neutrinos
export SCAN_PARAMS="-v -f 5 -a PARAM_SCAN \
         -e SBL -e KARMEN -e NOMAD -e CDHS -e MB300 -e ATM_COMP -e MINOS_NC \
         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01" \
         -p "DM41,-1,1,5,LOGSCALE"    -p "DM51,-1,1,5,LOGSCALE" \
         -m "DM41,DM51,TH14,TH24,TH15,TH25,TH34,TH35,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=16
#OUT_FILE=th23dm31-5f-nevid$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH13" $SCAN_PARAMS
#OUT_FILE=th13dm31-5f-nevid$SUFFIX.dat ./nu-batch -p "TH13,-2,-0.6,14,LOGSCALE" \
#                                 -p "DM31,1.5e-3,3.5e-3,10"    -m "TH23" $SCAN_PARAMS
#OUT_FILE=th23th13-5f-nevid$SUFFIX.dat ./nu-batch -p "TH23,0.4,1.1,20" \
#                                 -p "TH13,-2,-0.6,14,LOGSCALE" -m "DM31" $SCAN_PARAMS

# And now the same for 3 flavors only
export SCAN_PARAMS="-v -f 3 -a PARAM_SCAN -e SBL -e ATM_COMP -e MINOS_NC -m "DELTA_0" "
#./nu -p "TH23,0.4,1.1,20"          -p "DM31,1.5e-3,3.5e-3,20"    -m "TH13" $SCAN_PARAMS \
#     > ../2-smparams/th23dm31-3f-all$SUFFIX.dat &
#./nu -p "TH13,-2,-0.6,14,LOGSCALE" -p "DM31,1.5e-3,3.5e-3,20"    -m "TH23" $SCAN_PARAMS \
#     > ../2-smparams/th13dm31-3f-all$SUFFIX.dat &
#./nu -p "TH23,0.4,1.1,20"          -p "TH13,-2,-0.6,28,LOGSCALE" -m "DM31" $SCAN_PARAMS \
#     > ../2-smparams/th23th13-3f-all$SUFFIX.dat &
unset NU_SIZE
unset SCAN_PARAMS


# ---------------------------------------------------------------------------
#                       5-flavor fits
# ---------------------------------------------------------------------------

# dm41--dm51 plots
# ----------------

# Complete fit to all implemented experiments
export SP="-v -f 5 -a PARAM_SCAN   -t "DELTA_0=1.3" \
         -p "DM41,-1,1,40,LOGSCALE"         -p "DM51,-1,1,40,LOGSCALE" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -s "TH34,-1.5,-0.3,2,LOGSCALE"     -s "TH35,-1.5,-0.3,2,LOGSCALE" \
         -m "TH14,TH24,TH15,TH25,TH34,TH35,TH23,DM31,TH12,DELTA_0,DELTA_1,DELTA_2" "
export F=3p2
#export F=1p3p1
export NU_SIZE=100
#OUT_FILE=dm41dm51-all-$F$SUFFIX.dat ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC \
#  -e ICARUS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND
#OUT_FILE=dm41dm51-disapp-$F$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run $SP -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200

export SP="-v -f 5 -a PARAM_SCAN \
         -p "DM41,-1,1,40,LOGSCALE"         -p "DM51,-1,1,40,LOGSCALE" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -s "DELTA_0,0,4.7,3"               -s "DELTA_1,0,4.7,3" \
         -m "TH14,TH24,TH15,TH25,DELTA_0,DELTA_1" "
#OUT_FILE=dm41dm51-app-$F$SUFFIX.dat    MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run $SP -e ICARUS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND



# Individual appearance experiments
export SP="-v -f 5 -a PARAM_SCAN   -t "DELTA_0=1.3" \
         -p "DM41,-1,1,40,LOGSCALE"         -p "DM51,-1,1,40,LOGSCALE" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -m "TH14,TH24,TH15,TH25,DELTA_0,DELTA_1,DELTA_2" "
export NU_SIZE=32
#OUT_FILE=dm41dm51-lsnd-$F$SUFFIX.dat     ./compile-and-run $SP -e LSND   --no-nh
#OUT_FILE=dm41dm51-karmen-$F$SUFFIX.dat   ./compile-and-run $SP -e KARMEN --no-nh
#OUT_FILE=dm41dm51-nomad-$F$SUFFIX.dat    ./compile-and-run $SP -e NOMAD  --no-nh
#OUT_FILE=dm41dm51-icarus-$F$SUFFIX.dat   ./compile-and-run $SP -e ICARUS --no-nh
#OUT_FILE=dm41dm51-mb200-nu-app-full-$F$SUFFIX.dat    MBDEFS="NU_APP FULL_OSC" \
#                                         ./compile-and-run $SP -e MBall200 --no-nh
#OUT_FILE=dm41dm51-mb200-nubar-app-full-$F$SUFFIX.dat  MBDEFS="NUBAR_APP FULL_OSC" \
#                                         ./compile-and-run $SP -e MBall200 --no-nh
#OUT_FILE=dm41dm51-e776-reactors-$F$SUFFIX.dat  SBLDEFS="CHOOZ PV DC DB RENO" \
#                                         ./compile-and-run $SP -e E776 -e SBL -c DM31 
    # Use constraint from LBL reactors to avoid too large BG oscillations
unset NU_SIZE
unset SP
unset F


# Ue4Um4--Ue5Um5 plots
# --------------------

export SP="-v -f 5 -a PARAM_SCAN  -t "DM41=0.5,DM51=0.9" \
         -t "DELTA_0=1.3,TH14=0.785,TH15=0.785,TH34=0.01,TH35=0.01" \
         -p "Ue4Um4,-3,-0.6,48,LOGSCALE"    -p "Ue5Um5,-3,-0.6,48,LOGSCALE" \
         -s "TH14,-1.5,-0.11,3,LOGSCALE"    -s "TH15,-1.5,-0.11,3,LOGSCALE" \
         -s "DELTA_0,0,4.7,6"               -s "DELTA_1,0,4.7,6" \
         -m "TH14,TH15,DELTA_0,DELTA_1,DELTA_2" "
export F="dm0.5-0.9"
export NU_SIZE=100
# All experiments
#OUT_FILE=Ue4Um4_Ue5Um5-$F-all$SUFFIX.dat  ./compile-and-run $SP -m "TH23,DM31,TH12" \
#  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC \
#  -e ICARUS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  -m "TH34,TH35" --best-fit

# Appearance
#OUT_FILE=Ue4Um4_Ue5Um5-$F-app$SUFFIX.dat \
#  MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" ./compile-and-run $SP \
#  -e ICARUS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  --best-fit

# Disappearance
#OUT_FILE=Ue4Um4_Ue5Um5-$F-disapp$SUFFIX.dat \
#  MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" ./compile-and-run $SP  -m "TH23,DM31,TH12" \
#  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200 -m "TH34,TH35"
unset NU_SIZE
unset F
unset SP


# Phase dependence
export SP="-v -f 5 -a PARAM_SCAN -t "DM41=0.447,DM51=0.891" \
         -p "DELTA_0,0,6.28319,16"          -p "DELTA_1,0,6.28319,16" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -s "TH34,-1.5,-0.3,2,LOGSCALE"     -s "TH35,-1.5,-0.3,2,LOGSCALE" \
         -m "TH14,TH24,TH15,TH25,TH34,TH35" "
export NU_SIZE=40
#OUT_FILE=delta0delta1-3p2-sbl$SUFFIX.dat SBLDEFS="SBL BUGEY_SP GAL" ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  --best-fit
#OUT_FILE=delta0delta1-3p2-noatmminos$SUFFIX.dat ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  \
#  -e ICARUS -e SOLAR  --best-fit
#OUT_FILE=delta0delta1-3p2-all$SUFFIX.dat ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  \
#  -e ICARUS -e SOLAR -e MINOS_NC -e ATM_COMP  --best-fit

export SP="-v -f 5 -a PARAM_SCAN -t "DM41=0.447,DM51=0.891" \
         -p "DELTA_1,0,6.28319,16"          -p "DELTA_2,0,6.28319,16" \
         -s "TH14,-1.5,-0.3,2,LOGSCALE"     -s "TH15,-1.5,-0.3,2,LOGSCALE" \
         -s "TH24,-1.5,-0.3,3,LOGSCALE"     -s "TH25,-1.5,-0.3,3,LOGSCALE" \
         -s "TH34,-1.5,-0.3,2,LOGSCALE"     -s "TH35,-1.5,-0.3,2,LOGSCALE" \
         -m "TH14,TH24,TH15,TH25,TH34,TH35" "
export NU_SIZE=40
#OUT_FILE=delta1delta2-3p2-sbl$SUFFIX.dat SBLDEFS="SBL BUGEY_SP GAL" ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  --best-fit
#OUT_FILE=delta1delta2-3p2-noatmminos$SUFFIX.dat ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  \
#  -e ICARUS -e SOLAR  --best-fit
#OUT_FILE=delta1delta2-3p2-all$SUFFIX.dat ./compile-and-run $SP \
#  -e SBL -e C12 -e CDHS -e KARMEN -e NOMAD -e E776 -e MBall200 -e LSND  \
#  -e ICARUS -e SOLAR -e MINOS_NC -e ATM_COMP  --best-fit
unset NU_SIZE
unset SP



# ---------------------------------------------------------------------------
#                 Parameter goodness of fit tests
# ---------------------------------------------------------------------------


# chi^2 at global best fit point / goodness of fit tests
# ------------------------------------------------------

# NOTE: We use non-zero starting values for active-sterile mixing angles since
# otherwise, the minimizer might never find the right region of parameter space

export F="3p1"
export SP="-v -f 4 -a PARAM_SCAN \
           -t "TH14=0.01,TH24=0.01,DELTA_0=1.3" \
           -p "DM41,-1,1,20,LOGSCALE" \
           -m "DM41,TH14,TH24,DELTA_0,DELTA_1,DELTA_2" "
export SP2="-m "TH34,TH23,DM31,TH12" "

#export F="3p2"
##export F="1p3p1"
#export SP="-v -f 5 -a PARAM_SCAN \
#         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01,DELTA_0=1.3" \
#         -p "DM41,-1,1,10,LOGSCALE"         -p "DM51,-1,1,10,LOGSCALE" \
#         -s "DELTA_0,0,4.7,3"               -s "DELTA_1,0,4.7,3" \
#         -m "DM41,DM51,TH14,TH24,TH15,TH25,DELTA_0,DELTA_1,DELTA_2" "
#export SP2="-m "TH34,TH35,TH23,DM31,TH12" "

export NU_SIZE=20
#OUT_FILE="pg-$F-all$SUFFIX.dat"    MBDEFS="NU_APP NUBAR_APP COMBINED_APP NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP  $SP2  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200 \
#                          -e ICARUS -e KARMEN -e NOMAD -e E776 -e LSND
#OUT_FILE="pg-$F-disapp$SUFFIX.dat" MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP  $SP2  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200
#OUT_FILE="pg-$F-app$SUFFIX.dat"    MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run  $SP        -e MBall200 -e ICARUS -e KARMEN -e NOMAD -e E776 -e LSND

#OUT_FILE="pg-nombapp-$F-all$SUFFIX.dat"    MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP  $SP2  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200 \
#                          -e ICARUS -e KARMEN -e NOMAD -e E776 -e LSND
#OUT_FILE="pg-nombapp-$F-disapp$SUFFIX.dat" MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run  $SP  $SP2  -e SBL -e C12 -e CDHS -e ATM_COMP -e SOLAR -e MINOS_NC -e MBall200
#OUT_FILE="pg-nombapp-$F-app$SUFFIX.dat"    MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run  $SP        -e ICARUS -e KARMEN -e NOMAD -e E776 -e LSND
unset F
unset SP
unset NU_SIZE


# chi^2 for individual experiments at BFP
# ---------------------------------------

# 3+1 Global BF as of 2013-03-08
#export SP="-v -f 4 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-nh \
#           -t "TH12=0.595898,TH13=0.154085,TH23=0.760349,DELTA_0=-9.92547" \
#           -t "DM21=7.6e-05,DM31=-0.0022342,DM41=0.925377,TH14=0.15505" \
#           -t "TH24=0.176002,TH34=0.196718,DELTA_1=-1.2512,DELTA_2=0.179995" "
#export F="gbf"

# 3+2 Global BF as of 2013-03-08
#export SP="-v -f 5 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-nh \
#           -t "TH12=0.593181,TH13=0.154085,TH23=0.772835,DELTA_0=-3.31588" \
#           -t "DM21=7.6e-05,DM31=-0.00221302,DM41=0.872518,DM51=0.469161" \
#           -t "TH14=0.145541,TH15=0.127928,TH24=0.135006,TH25=-0.147626" \
#           -t "TH34=0.019367,TH35=-0.0283413,DELTA_1=1.5762,DELTA_2=-2.01901" "
#export F="gbf"

# 1+3+1 Global BF as of 2013-03-09
#export SP="-v -f 5 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-nh \
#           -t "TH12=0.592559,TH13=0.154085,TH23=0.790386,DELTA_0=-2.657" \
#           -t "DM21=7.6e-05,DM31=-0.00220524,DM41=-0.874018,DM51=0.47014" \
#           -t "TH14=0.149418,TH15=0.134225,TH24=0.1414,TH25=0.169049" \
#           -t "TH34=0.0259228,TH35=0.0299922,DELTA_1=1.61786,DELTA_2=1.43534" "
#export F="gbf"


## 3+2 Individual best fits
##export SP="-v -f 5 -a PARAM_SCAN \
##         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01,DELTA_0=1.3" \
##         -p "DM41,-1,1,10,LOGSCALE"         -p "DM51,-1,1,10,LOGSCALE" \
##         -s "DELTA_0,0,4.7,3"               -s "DELTA_1,0,4.7,3" \
##         -m "DM41,DM51,TH14,TH24,TH15,TH25,DELTA_0,DELTA_1" "
##export F="ibf"
##export NU_SIZE=10


# 3+1 Appearance BF as of 2013-03-08
#export SP="-v -f 4 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-ih \
#          -t "TH12=0.601264,TH13=0.154085,TH23=0.785398,DELTA_0=7.5807" \
#          -t "DM21=7.6e-05,DM31=0.0024,DM41=0.416084,TH14=0.0945393" \
#          -t "TH24=2.50002,DELTA_1=-6.33215,DELTA_2=6.99353" "
#export F="abf"

# 3+2 Appearance BF as of 2013-03-08
#export SP="-v -f 5 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-ih \
#           -t "TH12=0.601264,TH13=0.154085,TH23=0.785398,DELTA_0=1.73623" \
#           -t "DM21=7.6e-05,DM31=0.0024,DM41=1.23726,DM51=0.573875" \
#           -t "TH14=0.355847,TH15=0.0912437,TH24=0.0624929,TH25=0.785398" \
#           -t "DELTA_1=-0.0652215,DELTA_2=-2.94745" "
#export F="abf"

# 1+3+1 Appearance BF as of 2013-03-09
#export SP="-v -f 5 -a PARAM_SCAN -p "DM21,7.6e-05,7.6e-05,0" --no-ih \
#           -t "TH12=0.601264,TH13=0.154085,TH23=0.785398,DELTA_0=2.58482" \
#           -t "DM21=7.6e-05,DM31=0.0024,DM41=-1.75801,DM51=0.49615" \
#           -t "TH14=0.242295,TH15=0.0743694,TH24=0.0476796,TH25=0.785398" \
#           -t "DELTA_1=0.861767,DELTA_2=-1.88816" "
#export F="abf"


# Appearance experiments
#OUT_FILE=$F-lsnd$SUFFIX.dat    ./compile-and-run $SP -e LSND
#OUT_FILE=$F-karmen$SUFFIX.dat  ./compile-and-run $SP -e KARMEN
#OUT_FILE=$F-nomad$SUFFIX.dat   ./compile-and-run $SP -e NOMAD
#OUT_FILE=$F-icarus$SUFFIX.dat  ./compile-and-run $SP -e ICARUS
#OUT_FILE=$F-mb200-nu-app-full$SUFFIX.dat        MBDEFS="NU_APP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-mb200-nubar-app-full$SUFFIX.dat     MBDEFS="NUBAR_APP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-mb200-app-full$SUFFIX.dat           MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-e776$SUFFIX.dat    ./compile-and-run $SP -e E776
#OUT_FILE=$F-app$SUFFIX.dat                      MBDEFS="NU_APP NUBAR_APP COMBINED_APP FULL_OSC" \
#  ./compile-and-run $SP -e MBall200 -e LSND -e KARMEN -e NOMAD -e ICARUS -e E776

# Disappearance experiments + combinations
#OUT_FILE=$F-mb200-nu-disapp-full$SUFFIX.dat     MBDEFS="NU_DISAPP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-mb200-nubar-disapp-full$SUFFIX.dat  MBDEFS="NUBAR_DISAPP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-mb200-disapp-full$SUFFIX.dat        MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#                               ./compile-and-run $SP -e MBall200
#OUT_FILE=$F-cdhs$SUFFIX.dat    ./compile-and-run $SP -e CDHS
#OUT_FILE=$F-c12$SUFFIX.dat     ./compile-and-run $SP -e C12
#OUT_FILE=$F-solar$SUFFIX.dat   ./compile-and-run $SP -e SOLAR
#OUT_FILE=$F-atm$SUFFIX.dat     ./compile-and-run $SP -e ATM
#OUT_FILE=$F-minos$SUFFIX.dat   ./compile-and-run $SP -e MINOS_NC
#OUT_FILE=$F-gal$SUFFIX.dat         SBLDEFS="GAL" \
#                               ./compile-and-run $SP -e SBL
#OUT_FILE=$F-sbl-rectors$SUFFIX.dat SBLDEFS="SBL BUGEY_SP" \
#                               ./compile-and-run $SP -e SBL
#OUT_FILE=$F-lbl-rectors$SUFFIX.dat SBLDEFS="CHOOZ PV DC DB RENO KAML" \
#                               ./compile-and-run $SP -e SBL
#OUT_FILE=$F-sbl$SUFFIX.dat     ./compile-and-run $SP -e SBL
#OUT_FILE=$F-disapp$SUFFIX.dat MBDEFS="NU_DISAPP NUBAR_DISAPP FULL_OSC" \
#  ./compile-and-run $SP -e MBall200 -e CDHS -e C12 -e SOLAR -e ATM -e MINOS_NC -e SBL
unset F
unset SP
unset NU_SIZE


unset SCAN_PARAMS


# ---------------------------------------------------------------------------
#                              MCMC Tests
# ---------------------------------------------------------------------------

# Standard oscillation fits
# -------------------------

#OUTPUT_PATH=/temp/jkopp/sterile-nu/mcmc/
#export NU_SIZE=4
#export OUT_FILE="mcmc-log"
#SBLDEFS="CHOOZ DB_3F DC RENO KAML" \
#  ./compile-and-run -M -l \
#                    -f 3 --no-ih -a MCMC \
#                    -e SBL -e SOLAR -e ATM_COMP -e T2K -e MINOS_2016 \
#                    -p "DM21,5e-5,1e-4,15" \
#                    -p "DM31,2.0e-3,3.0e-3,15" \
#                    -p "DELTA_0,0,2*pi,8" \
#                    -p "TH12,asin(sqrt(0.2)),asin(sqrt(0.4)),20" \
#                    -p "TH13,0,0.5*asin(sqrt(0.15)),20" \
#                    -p "TH23,asin(sqrt(0.2),asin(sqrt(0.7)),20" \
#                    -o $OUTPUT_PATH/3f$SUFFIX.dat
#unset NU_SIZE
#unset OUT_FILE

# Conventional frequentist fits for comparison
#OUT_FILE="dm31th23$SUFFIX.dat" SBLDEFS="CHOOZ DB_3F DC RENO KAML" \
#  ./compile-and-run -M -l -f 3 --no-ih -a PARAM_SCAN \
#                                  -e SBL -e SOLAR -e ATM_COMP -e T2K -e MINOS_2016 \
#                                  -p "DM31,2.0e-3,3.0e-3,20" \
#                                  -p "TH23,asin(sqrt(0.2),asin(sqrt(0.7)),20" \
#                                  -m "TH12,TH13,DELTA_0,DM21"
#OUT_FILE="dm21th12$SUFFIX.dat" SBLDEFS="CHOOZ DB_3F DC RENO KAML" \
#  ./compile-and-run -M -l -f 3 --no-ih -a PARAM_SCAN \
#                                  -e SBL -e SOLAR -e ATM_COMP -e T2K -e MINOS_2016 \
#                                  -p "DM21,5e-5,1e-4,20" \
#                                  -p "TH12,asin(sqrt(0.2)),asin(sqrt(0.4)),20" \
#                                  -m "TH13,TH23,DELTA_0,DM31"
#OUT_FILE="th13delta$SUFFIX.dat" SBLDEFS="CHOOZ DB_3F DC RENO KAML" \
#  ./compile-and-run -M -l -f 3 --no-ih -a PARAM_SCAN \
#                                  -e SBL -e SOLAR -e ATM_COMP -e T2K -e MINOS_2016 \
#                                  -p "TH13,0,0.5*asin(sqrt(0.15)),20" \
#                                  -p "DELTA_0,0,2*pi,8" \
#                                  -m "TH12,TH23,DM21,DM31"


# Sterile neutrino fits
# ---------------------

#export SP="-v -f 5 -a MCMC \
#         -t "TH14=0.01,TH24=0.01,TH15=0.01,TH25=0.01,DELTA_0=1.3" \
#         -p "DM41,-1,1,10,LOGSCALE"         -p "DM51,-1,1,10,LOGSCALE" \
#         -s "DELTA_0,0,4.7,3"               -s "DELTA_1,0,4.7,3" \
#         -m "DM41,DM51,TH14,TH24,TH15,TH25,DELTA_0,DELTA_1,DELTA_2" "
#export SP2="-m "TH34,TH35,TH23,DM31,TH12" "
#
#./nu  $SP $SP2  -e C12 -e SBL -e CDHS -e SOLAR -e MINOS_2016 -e MBall200 \
#                -e ICARUS-2014 -e KARMEN -e NOMAD -e E776 -e LSND -e ATM_COMP
#unset SP2
#unset SP


OUTPUT_PATH=/temp/jkopp/sterile-nu/mcmc/
export SP="-f 4 --no-ih -a MCMC \
                    -p "DM41,-1.4,1.4,56,LOGSCALE" \
                    -p "TH13,0,0.3,10" \
                    -p "TH14,0,0.6,20" "
export NU_SIZE=4
export OUT_FILE="mcmc-log"
###SBLDEFS="SBL BUGEY_SP" ./compile-and-run -M -l $SP -e SBL \
###                           -o $OUTPUT_PATH/dm41th13th14-mytest$SUFFIX.dat


#SBLDEFS="SBL BUGEY_SP CHOOZ PV DC DB RENO DANNS" ./compile-and-run -M -l $SP -e SBL \
#                           -o $OUTPUT_PATH/dm41th13th14-sbllblreactors$SUFFIX.dat
#SBLDEFS="CHOOZ PV DC DB RENO" ./compile-and-run -M -l $SP -e SBL \
#                           -o $OUTPUT_PATH/dm41th13th14-lblreactors$SUFFIX.dat
#SBLDEFS="GALP" ./compile-and-run -M -l $SP -e SBL \
#                           -o $OUTPUT_PATH/dm41th13th14-gal$SUFFIX.dat
#SBLDEFS="SBL BUGEY_SP DANSS" ./compile-and-run -M -l $SP -e SBL \
#                           -o $OUTPUT_PATH/dm41th13th14-sblreactors$SUFFIX.dat
#SBLDEFS="" ./compile-and-run -M -l $SP -e C12 \
#                           -o $OUTPUT_PATH/dm41th13th14-c12$SUFFIX.dat

export SP="$SP -s "DELTA_0,0,4.7,3" -s "DELTA_1,0,4.7,3" -m "DELTA_0,DELTA_1""
#OUT_FILE=dm41th13th14-solar-kaml$SUFFIX.dat SBLDEFS="KAML" \
#  ./compile-and-run -l $SP -e SBL -e SOLAR -m "TH12,TH24,TH34"
#OUT_FILE=dm41th13th14-disapp-e$SUFFIX.dat SBLDEFS="SBL CHOOZ PV DC DB RENO BUGEY_SP GAL KAML"
#  ./compile-and-run -l $SP -e SBL -e SOLAR -e C12  -m "TH12,TH24,TH34"
unset SP
unset NU_SIZE
unset OUT_FILE


