#!/bin/bash
globes=$HOME/papers/sterile-nu/globes/bin/globes
SUFFIX=""
export MBJKDEFS="OSC_NORM OSC_BG OSC_NUMU"

cd 0-code/

echo "******** Warnings in C code **************"
grep -d skip "FIXME" *
echo "******************************************"
grep "FIXME" $(find glb/* -name "*.glb")
echo "******************************************"
echo


#---------------------------------------------------------------------
# Spectra
#---------------------------------------------------------------------

# 3+1 fits
# --------

## MiniBooNE best fit point for 3+1 (oscillations only)
## see dm41s22thmueUm4-mbjk-3p1-numuosc.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=0.125893,Ue4=0.156304,Um4=0.794328" \
#           -t "MA_OVER_M4=0.7,M4_GAMMA=1e-20" "
#unbuffer ./nu $SP -e MB_JK |  tee ../1-spectra/mbjk-3p1.dat
#
## Best fit point w/o LSND
## see bfp-3p1-nolsnd.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=945.76,Ue4=-0.00404154,Um4=0.285147" \
#           -t "MA_OVER_M4=0.7,M4_GAMMA=1e-20" "
#unbuffer ./nu $SP -e MB_JK |  tee ../1-spectra/mbjk-3p1-nolsnd.dat


# Oscillation + decay fits
# ------------------------

## MiniBooNE best fit point for oscillation + decay
## see bfp-mbjk.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=0.00970712,Ue4=0.57988,Um4=0.0269327" \
#           -t "MA_OVER_M4=0.898224,M4_GAMMA=0.726146" "
#unbuffer ./nu $SP -e MB_JK     |  tee ../1-spectra/mbjk-mbbf.dat
#
## MiniBooNE benchmark point for oscillation + decay
## see dm41Ue4Um4-mbjk-m4G2-MAM40.9.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=160000,Ue4=0.3,Um4=0.03,MA_OVER_M4=0.9,M4_GAMMA=2" "
#unbuffer ./nu $SP -e MB_JK     |  tee ../1-spectra/mbjk-bench.dat
#
## Best fit point w/o LSND
## see bfp-nolsnd.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=180812,Ue4=0.0473404,Um4=0.0652699" \
#           -t "MA_OVER_M4=0.821205,M4_GAMMA=2.09701" "
#unbuffer ./nu $SP -e MB_JK     |  tee ../1-spectra/mbjk-nolsnd.dat
#
## Best fit point w/o cosmology
## see bfp-nocosmo.dat.gz
#export SP="-f 4 -a SPECTRUM \
#           -t "DM41=9413.84,Ue4=0.1343,Um4=0.0388134" \
#           -t "MA_OVER_M4=0.888247,M4_GAMMA=0.871435" "
#unbuffer ./nu $SP -e MB_JK     |  tee ../1-spectra/mbjk-nocosmo.dat


#---------------------------------------------------------------------
# Exclusion regions in DM41-Ue4-Um4  -- projected
#---------------------------------------------------------------------

#export SP="-f 4 -a PARAM_SCAN --no-ih \
#           -t "M4_GAMMA=1.,MA_OVER_M4=0.7" \
#           -m "M4_GAMMA,MA_OVER_M4" \
#           -p "DM41,3.,6.,15,LOGSCALE" \
#           -p "Ue4,0.,0.3,30" \
#           -p "Um4,0.,0.2,20" "
#OUT_FILE=dm41Ue4Um4-all-proj$SUFFIX.dat ./compile-and-run -l $SP \
#           -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#           -e DECAY_KINEMATICS -e FREE_STREAMING


#---------------------------------------------------------------------
# Exclusion regions in DM41-Ue4-Um4  -- unprojected
#---------------------------------------------------------------------

#for M4G in 0.1 0.2 1 2 10
#do
#  for MAM4 in 0.1 0.5 0.7 0.9
#  do
#    export SP="-f 4 -a PARAM_SCAN --no-ih \
#               -t "M4_GAMMA=$M4G,MA_OVER_M4=$MAM4", \
#               -p "DM41,3.,6.,15,LOGSCALE" \
#               -p "Ue4,0.,0.3,30" \
#               -p "Um4,0.,0.2,20" "
#    export SUFFIX="-m4G$M4G-MAM4$MAM4"
#    echo "Launching runs at m4*\\Gamma=$M4G, m_{A'}/m_4 = $MAM4 ..."
#    unbuffer ./nu $SP -e E776              > ../8-oscdecay/dm41Ue4Um4-e776$SUFFIX.dat &
#    unbuffer ./nu $SP -e ICARUS-2014       > ../8-oscdecay/dm41Ue4Um4-icarus$SUFFIX.dat &
#    unbuffer ./nu $SP -e OPERA             > ../8-oscdecay/dm41Ue4Um4-opera$SUFFIX.dat &
#    unbuffer ./nu $SP -e LSND_IVAN         > ../8-oscdecay/dm41Ue4Um4-lsnd-ivan$SUFFIX.dat &
#    unbuffer ./nu $SP -e KARMEN_IVAN       > ../8-oscdecay/dm41Ue4Um4-karmen-ivan$SUFFIX.dat &
#    unbuffer ./nu $SP -e MB_JK             > ../8-oscdecay/dm41Ue4Um4-mbjk$SUFFIX.dat &
#    unbuffer ./nu $SP -e DECAY_KINEMATICS  > ../8-oscdecay/dm41Ue4Um4-betadecay$SUFFIX.dat &
#    unbuffer ./nu $SP -e FREE_STREAMING    > ../8-oscdecay/dm41Ue4Um4-freestreaming$SUFFIX.dat &
#    unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                      -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                           > ../8-oscdecay/dm41Ue4Um4-nolsnd$SUFFIX.dat &
#    unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#                      -e DECAY_KINEMATICS  > ../8-oscdecay/dm41Ue4Um4-nocosmo$SUFFIX.dat &
#    unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#                      -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                           > ../8-oscdecay/dm41Ue4Um4-all$SUFFIX.dat &
#  done
#done
#
## Higher resolution runs for the paper
#for M4G in 0.1 0.2 1 2 10
#do
#  for MAM4 in 0.9
#  do
#    export SP="-f 4 -a PARAM_SCAN --no-ih \
#               -t "M4_GAMMA=$M4G,MA_OVER_M4=$MAM4", \
#               -p "DM41,3.,6.,15,LOGSCALE" \
#               -p "Ue4,0.,0.15,30" \
#               -p "Um4,0.,0.15,15" "
#    export SUFFIX="-m4G$M4G-MAM4$MAM4-hires"
#    echo "Launching runs at m4*\\Gamma=$M4G, m_{A'}/m_4 = $MAM4 ..."
#    unbuffer ./nu $SP -e FREE_STREAMING    > ../8-oscdecay/dm41Ue4Um4-freestreaming$SUFFIX.dat &
#    unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                      -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                           > ../8-oscdecay/dm41Ue4Um4-nolsnd$SUFFIX.dat &
#    unbuffer ./nu $SP -e MB_JK             > ../8-oscdecay/dm41Ue4Um4-mbjk$SUFFIX.dat &
#  done
#done


#---------------------------------------------------------------------
# Best fit points
#---------------------------------------------------------------------

#export SP="-f 4 -a PARAM_SCAN --no-ih -v \
#           -t "M4_GAMMA=1.,MA_OVER_M4=0.7" \
#           -m "DM41,M4_GAMMA,MA_OVER_M4,Ue4,Um4" \
#           -p "DM41,3.,6.,3,LOGSCALE" \
#           -s "M4_GAMMA,-1,3,4,LOGSCALE" \
#           -s "MA_OVER_M4,0.1,0.9,4" \
#           -s "Ue4,0.,0.3,9" \
#           -s "Um4,0.,0.2,6" "
#export SUFFIX=""
#unbuffer ./nu $SP -e E776              > ../8-oscdecay/bfp-e776$SUFFIX.dat &
#unbuffer ./nu $SP -e ICARUS-2014       > ../8-oscdecay/bfp-icarus$SUFFIX.dat &
#unbuffer ./nu $SP -e OPERA             > ../8-oscdecay/bfp-opera$SUFFIX.dat &
#unbuffer ./nu $SP -e LSND_IVAN         > ../8-oscdecay/bfp-lsnd-ivan$SUFFIX.dat &
#unbuffer ./nu $SP -e KARMEN_IVAN       > ../8-oscdecay/bfp-karmen-ivan$SUFFIX.dat &
#unbuffer ./nu $SP -e MB_JK             > ../8-oscdecay/bfp-mbjk$SUFFIX.dat &
#unbuffer ./nu $SP -e DECAY_KINEMATICS  > ../8-oscdecay/bfp-betadecay$SUFFIX.dat &
#unbuffer ./nu $SP -e FREE_STREAMING    > ../8-oscdecay/bfp-freestreaming$SUFFIX.dat &
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                  -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                       > ../8-oscdecay/bfp-nolsnd$SUFFIX.dat &
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                  -e DECAY_KINEMATICS  > ../8-oscdecay/bfp-nolsnd-nocosmo$SUFFIX.dat &
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#                  -e DECAY_KINEMATICS  > ../8-oscdecay/bfp-nocosmo$SUFFIX.dat &
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#                  -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                       > ../8-oscdecay/bfp-all$SUFFIX.dat &
#
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                                       > ../8-oscdecay/bfp-nolsnd-noaux$SUFFIX.dat &
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e LSND_IVAN -e KARMEN_IVAN -e MB_JK \
#                                       > ../8-oscdecay/bfp-noaux$SUFFIX.dat &
#
#
## Standard 3+1 fits
#export SP="-f 4 -a PARAM_SCAN --no-ih -v \
#           -t "M4_GAMMA=1e-20,MA_OVER_M4=0.7" \
#           -m "DM41,Ue4,Um4" \
#           -p "DM41,3.,6.,3,LOGSCALE" \
#           -s "Ue4,0.,0.3,9" \
#           -s "Um4,0.,0.2,6" "
#export SUFFIX=""
#unbuffer ./nu $SP -e E776 -e ICARUS-2014 -e OPERA -e KARMEN_IVAN -e MB_JK \
#                  -e DECAY_KINEMATICS -e FREE_STREAMING \
#                                       > ../8-oscdecay/bfp-3p1-nolsnd$SUFFIX.dat &



