#!/bin/bash
#Usage: qsub nu-batch <arguments>
CODE_PATH=$HOME/papers/sterile-nu/sim/0-code/
DATA_PATH=$HOME/papers/sterile-nu/sim/results

# Export all environment variables
#$ -V

# Specify location of output and error files
#$ -o /home/lin/jkopp/papers/sterile-nu/sim/results
#$ -e /home/lin/jkopp/papers/sterile-nu/sim/results
#$ -m ae
#$ -M jkopp@mpi-hd.mpg.de

echo "Starting job run-nu" $@ "at: "
date
echo
#echo "System type:"
#echo "------------"
#cat /proc/cpuinfo

# Determine name of output file
if [[ -z $OUT_FILE ]]; then
  OUT_FILE=$DATA_PATH"/"$(mktemp -u nu-XXXXXXXX)".dat"
else
  OUT_FILE=$DATA_PATH"/"$OUT_FILE
fi
echo "Output file: $OUT_FILE"

# Determine name of executable
if [[ -z $EXE_FILE ]]; then
  EXE_FILE=nu
fi
echo "Executable:  $EXE_FILE"


ulimit -c 0  # Switch off core dumps
cd $CODE_PATH
$CODE_PATH/$EXE_FILE $@ > $OUT_FILE

echo
echo "Job finished at: "
date

