#!/bin/bash

# Set paths
export DATA_PATH=$(pwd)/../results
export CODE_PATH=$(pwd)
cd $DATA_PATH

if [[ -z $NU_SIZE ]]; then
  NU_SIZE=1;
fi

# For parallel jobs, loop over all slices
for (( I=0; $I < NU_SIZE; I++ )); do

  export NU_RANK=$I
  if (( NU_SIZE > 1 )); then
    export OF="${OUT_FILE%%.dat}_${NU_RANK}.dat"
  else
    export OF="${OUT_FILE}";
  fi
  export CONDOR_SCRIPT="condor_script_${OF%%.dat}"

  echo "Submitting with options $@, slice $NU_RANK / $NU_SIZE."
  echo "Output file: $OF"

  # Generate condor submit script
  cat <<-EOF > $CONDOR_SCRIPT
Universe                = grid
GridResource            = gt2 fnpcosg1.fnal.gov/jobmanager-condor
Executable              = $CODE_PATH/nu
Arguments               = $@
Remote_InitialDir       = $CODE_PATH
Output                  = $DATA_PATH/$OF
Error                   = $DATA_PATH/$OF.err
Log                     = $DATA_PATH/$OF.log
transfer_executable     = False
Environment             = "NU_RANK=$NU_RANK;NU_SIZE=$NU_SIZE"
Notification            = always
Notify_User             = jkopp@fnal.gov
globusrsl               = (jobtype=single)(maxwalltime=999)
QUEUE
EOF

  # Submit job
  condor_submit -debug $CONDOR_SCRIPT
done

